eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka
spring:
  application:
    name: notification-service
  sleuth:
    integration:
      enabled: true
    sampler:
      probability: 1
  zipkin:
    base-url: http://localhost:9411
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: notificationTopic
    consumer:
      group-id: notificationId
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring:
          json:
            type:
              mapping: event='com.demoapigateway.notificationservice.OrderPlacedEvent'
            trusted:
              packages: '*'

server:
  port: 0

management:
  endpoints:
    web:
      exposure:
        include: prometheus
