server:
  port: 8181
eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@discovery-server:8761/eureka

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak-server:8080/realms/spring-boot-microservices-realm
  zipkin:
    base-url: http://zipkin-server:9411