eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/inventory_service
    username: root
    password: m4sql4dm1n
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  application:
    name: inventory-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0 # 100%
server:
  port: 0

management:
  endpoints:
    web:
      exposure:
        include: prometheus